### ISSUE TITLE
Error in processing generated output

### ISSUE THREAD

**Issue by SM-26** [dailydaniel/logseq-plugin-ai-query#1]
Hello,

very nice idea
I tried to test it out, both with and without OpenAI API key

I always get errors:

```
Error in processing generated output

Error: Unable to generate text using OpenAI API. Request failed with status code 429
```

```
Error in processing generated output

Error: Unable to generate text using the custom model. Failed to fetch model ID from the custom server.
```

in addition, I think that adding a button to the plugin in the top bar could be helpful

Thanks in advance.

**Comment by dailydaniel** [comment]
@SM-26 Thank you very much for your feedback! 
Please provide an example of the description of the query that you give to the model. 
And did I understand correctly that the first error is in the case with openai key, the second - without?

About the button for the plugin, I will gladly accept a pull request)

**Comment by dailydaniel** [comment]
@SM-26 Hello,

I've tested both openai and custom model, it worked for me. 
[IMG_0187.GIF.zip](https://github.com/user-attachments/files/18162592/IMG_0187.GIF.zip)
this is zip of gif i made with my tests, file was 11mb so i archived it

**Comment by SM-26** [comment]
small update, I found the problem
it was my network configuration.
